### ISSUE TITLE
[Feature Request] Night mode switch :(

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/makedeb.org#1]
Very nice site, simply too bright. A toggle switch would be appreciated, or if possible even detecting the system theme settings.

**Comment by hwittenborn** [comment]
I feel like this deserves a comment considering how long the issue's been open:

If I'm being honest, this probably won't be added unless it gets implemented by someone else. This would be a serious architectural change to how the styling is done, and it's something I don't have much motivation to do, primarily because I don't care too much about dark mode myself anymore. I know that's probably not the best answer, but it's all I can really give right now.
